---
title: "Retroalimentación colaborativa"
output: distill::distill_article
---

<div style="text-align: justify"> En este espacio se recopilan las necesidades y sugerencias de la comunidad en torno a los recursos disponibles. El objetivo es identificar estudios o herramientas que hacen falta, de modo que cualquier persona interesada en contribuir pueda retomarlos y desarrollarlos.

Los recursos están desarrollados en R, pero si no tienes experiencia previa con este lenguaje de programación, podemos ayudarte en el proceso.


Si deseas **<span style="color:#55828B">solicitar la creación de alguna herramienta o recurso </span>**, **<span style="color:#55828B">informar que ya estás trabajando en alguna de ellas</span>** o **<span style="color:#55828B">encontraste algún error</span>**, por favor llena el <a href="https://forms.gle/8VrPyzcTdCBj5dtg9" target="_blank">formulario de retroalimentación.</a>


Si deseas **<span style="color:#55828B">subscribirte </span>** al boletín y recibir alertas cada que se incorpore alguna herramienta nueva, por favor llena el <a href="https://forms.gle/boBFetRedKsUExLx7" target="_blank">formulario.</a></div> 





## Última actualizacion

**23 de agosto 2025**    
* Se incluyó la calculadora de error de medición        
* Se incluyó la herramienta para consensuar la edad        
* Se incluyeron todas las calculadoras disponibles en el artículo "Bridging research and practice: A critical review of biological profile estimation methods applied to the Mexican population."        




### Correo de contacto
afrelacional@gmail.com
