---
title: "Herramientas para estimar el perfil biológico"
description: |
date: "`r Sys.Date()`"
output: distill::distill_article
---

# Relevancia

<div style="text-align: justify"> Las herramientas presentadas a continación son  especialmente útiles en el contexto mexicano debido a la crisis humanitaria en materia de identificación de Personas Fallecidas. Al cierre de 2023, en México había almacenados un total de 15,878 cadáveres y 12,938 restos de seres humanos en diferentes lugares como anfiteatros, laboratorios, centros de resguardo forense u homólogos, y agencias funerarias (INEGI, 2024). Estos datos reflejan la necesidad de contar con herramientas que permitan al personal Forense (Antropólogos Físicos, Médicos y Odontólogos) tomar decisiones ágiles y facilitar la estimación del Perfil Biológico basada en evidencia científica para población mexicana, sobre todo de cara al gran número tanto de cadáveres completos, así como de restos óseos (completos y fragmentados) que dificultan la labor forense. 

Además, la limitada infraestructura y recursos técnicos en el país exigen métodos prácticos, precisos y adaptados a las condiciones locales. Al ofrecer métodos validados y automatizados para estimar edad, sexo y estatura en población mexicana, esperamos que estas herramientas facilite la obtención y mejore la precisión de los datos obtenidos durante el análisis posmortem y con ello se contribuya a incrementar el número de identificaciones a nivel nacional.</div>    


# Aportes 
<div style="text-align: justify"> Algunos aportes de estas herramientas son:

* **Automatización de Cálculos:** Reduce el tiempo manual dedicado a los análisis, al procesar instantáneamente los datos ingresados, minimizando errores humanos y permitiendo obtener resultados fiables con rapidez.    
* **Adaptabilidad a Datos Parciales:** Permite trabajar con Personas Fallecidas completas, incompletas o fragmentadas, utilizando los elementos anatómicos disponibles.    
* **Estimar Intervalos de Confianza y Errores:** Las calculadoras incluyen métricas de precisión y error asociadas a cada estimación, facilitando la evaluación de la fiabilidad de los resultados en contextos forenses complejos.    
* **Comparación de Métodos:** Permite comparar diferentes métodos validados para un mismo componente biológico, ayudando a seleccionar el más adecuado según la disponibilidad de restos y características del caso.    
* **Facilita la Documentación Forense:** Permite generar reportes estandarizados y detallados que incluyen el método y mediciones utilizadas, y resultados, mejorando la calidad, transparencia y reproducibilidad de los informes periciales. </div>    



# Herramientas disponibles

<a href="https://antropologia-relacional.github.io/forense/ArchivoPB.html" class="icon-link" target="_blank" rel="noopener"><i class="fa-solid fa-folder-open"></i>&nbsp;Archivo del perfil biológico mexicano</a>

<a href="https://antropologia-relacional.github.io/apps/wSaltoRana/" class="icon-link" target="_blank" rel="noopener"><i class="fa-solid fa-chart-column"></i>&nbsp; Gráfico para consensuar la estimación de edad</a>

<a href="https://antropologia-relacional.github.io/apps/wTEM/" class="icon-link" target="_blank" rel="noopener"><i class="fa-solid fa-calculator"></i>&nbsp; Calculadora para estimar el Error Técnico de Medida</a>

```{r, echo=FALSE, layout="l-page"}
#los iconos los obtuve de: 
#  https://fontawesome.com/search?o=r
```



<br>
<br>

# Referencias
Instituto Nacional de Estadística y Geografía (INEGI). (2024, 13 de septiembre). Servicios periciales y servicio médico forense 2024 (Comunicado de prensa núm. 557/24). https://www.inegi.org.mx



### Colaboradoras

**<span style="color:#55828B">María García-Velasco.</span>** Departamento de Medicina Legal, Psiquiatría y Patología. Laboratorio de Antropología Forense. Universidad Complutense de Madrid.   

**<span style="color:#55828B">Mónica Silvy Morales Ríos.</span>** Instituto de Medicina Forense, Universidad Veracruzana.    

**<span style="color:#55828B">Jessica Alejandra Campos-Rodríguez.</span>** Escuela Nacional de Ciencias Forenses, Universidad Nacional Autónoma de México.     

**<span style="color:#55828B">Arodi Farrera.</span>** Instituto de Investigaciones Antropológicas, Universidad Nacional Autónoma de México. 





